services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: persons
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U user -d persons"]
      interval: 5s
      retries: 5

  migrate:
    build: .
    entrypoint: ["sh", "./apply-migrations.sh"]
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  app:
    build: .
    entrypoint: ["./person-api"]
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "${SERVER_PORT}:8080"
    depends_on:
      - migrate
    restart: on-failure

volumes:
  db-data:
