services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: persons
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -p 5432 -U user -d persons"]
      interval: 5s
      retries: 5

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:8080"
    restart: on-failure

volumes:
  db-data:
